version: "3.9"

services:
  server1:
    build: ./server
    image: server:latest
    container_name: server1
    environment:
      - SERVER_ID=server1
    networks:
      - lb_network

  server2:
    build: ./server
    image: server:latest
    container_name: server2
    environment:
      - SERVER_ID=server2
    networks:
      - lb_network

  server3:
    build: ./server
    image: server:latest
    container_name: server3
    environment:
      - SERVER_ID=server3
    networks:
      - lb_network

  load_balancer:
    build: ./load_balancer
    image: load_balancer:latest
    container_name: load_balancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - LB_NETWORK=lb_network
      # **Explicitly pass your Compose project & (logical) service name**
      - LB_PROJECT=load-balancer-assignment
      - LB_SERVICE=server
      - ENABLE_HEAL=false
      - HEALTH_INTERVAL=5
    networks:
      - lb_network

networks:
  lb_network:
    name: lb_network
    driver: bridge
